# Generated by Django 3.2.5 on 2021-08-24 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=10)),
                ('store_holder', models.CharField(max_length=50)),
                ('store_phoneNumber', models.CharField(max_length=10)),
                ('store_address', models.CharField(max_length=100)),
                ('store_email', models.EmailField(default='', help_text='必需的。 添加有效的電子郵件地址', max_length=60, unique=True, verbose_name='郵件信箱')),
                ('store_notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_store_name', models.CharField(max_length=20)),
                ('vendor_holder_name', models.CharField(max_length=10)),
                ('vendor_phone_number', models.CharField(max_length=20)),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItem_name', models.CharField(max_length=50)),
                ('menuItem_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('menuItem_meals_size', models.CharField(choices=[('BG', 'Big'), ('MD', 'Middle'), ('SM', 'Small')], default='Big', max_length=9)),
                ('menuItem_notes', models.TextField(blank=True, default='')),
                ('menuItem_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='polls.store')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_name', models.CharField(max_length=30)),
                ('ingredients_price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ingredients_unit', models.CharField(choices=[('公克', 'Gram'), ('公斤', 'Kilogram'), ('台斤', 'catty'), ('毫克', 'Milligrams')], default='公克g', max_length=9)),
                ('ingredients_notes', models.TextField(blank=True, default='')),
                ('ingredients_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_menu_items', to='polls.vendor')),
            ],
        ),
    ]
